### ISSUE TITLE
Error using test fastas and example command

### ISSUE THREAD

**Issue by vrou1995** [carden24/V-Xtractor#2]
Hi,

Thank you for developing this software. However, I am consistently getting this error message:

Use of uninitialized value $values in pattern match (m//) at vxtractor.pl line 501, <IN> chunk 18.
Argument "les,HMMs" isn't numeric in addition (+) at vxtractor.pl line 489, <IN> chunk 18.
Argument "tedHMMER" isn't numeric in addition (+) at vxtractor.pl line 489, <IN> chunk 18.

Any idea why this might be happening? I am operating in a conda env with HMMER v3.

Many thanks,

Vincent

**Comment by carden24** [comment]
Hi Vincent,
The software was developed by Martin Hartman while he was a postdoc at the Mohn lab and that is why I put it in the lab repository but I did not do any of the coding, I do not even know how to code in perl.  If you are using conda, why don't you create an environment with the version of HMMER used by that time. Maybe the problem is that the HMMs are formatted differently.   You can always contact Martin if you have more questions. This is [his website](http://www.microbiome.ch/) . Sorry I could not be of more help
